From: Pn Prod vROPS <prod.vrops@3test.net>
To: *SmartOps Fusion Three UK IT Unix <SmartOpsFusionThreeUKITUnix@amdocs.com>
Subject: Task: pn01log04 RedHat Linux SL01LOGFR04 Memory Utilization critical

New alert was generated at Tue Aug 26 17:48:51 UTC 2025:
Info:pn01log04 VirtualMachine is acting abnormally since Tue Aug 26 17:48:51 UTC 2025 and was last updated at Tue Aug 26 17:48:51 UTC 2025

Alert Definition Name: Memory Utilization - Critical
Alert Definition Description: 
Object Name : pn01log04
Object Type : VirtualMachine
Alert Impact: health
Alert State : critical
Alert Type : Application
Alert Sub-Type : Performance
Object Health State: 4.0
Object Risk State: 1.0
Object Efficiency State: 1.0
Control State: Open
Symptoms:
SYMPTOM SET - self
Conditions - 
Object Name	Object ID	Metric	Message Info
pn01log04	122ccd51-cd93-4458-98e6-d4f0163e64f0	Memory|Usage (%)	> 90.0

Recommendations: 
Notification Rule Name: Memory Utilization Alert PN01_VMC2 RHEL Server
Notification Rule Description: Memory Utilization Alert PN01_VC2 RHEL Server
Alert ID : 45a8200e-c858-499c-86cb-04182a189b91
VCOps Server - pn01vrops8

Alert details
