From: monitoring@infra.example.com

To: storage-team@example.com

Subject: [ALERT] Disk Utilization High on linux1


Hello Team,

The monitoring system has detected that disk utilization on /var for linux1 has exceeded 95% for the past 30 minutes.

To avoid an outage, please extend the /var filesystem by 50GB. Incident INC654321 raised for this issue.

Please review and take necessary action.

Thanks,
Infra Monitoring System