New alert was generated at Wed Aug 27 01:08:59 UTC 2025:
Info:linux1 VirtualMachine is acting abnormally since Wed Aug 27 01:08:59 UTC 2025 and was last updated at Wed Aug 27 01:08:59 UTC 2025

Alert Definition Name: Memory Utilization - Critical
Alert Definition Description: 
Object Name : linux1
Object Type : VirtualMachine
Alert Impact: health
Alert State : critical
Alert Type : Application
Alert Sub-Type : Performance
Object Health State: 4.0
Object Risk State: 1.0
Object Efficiency State: 1.0
Control State: Open
Symptoms:
SYMPTOM SET - self
Conditions - 
Object Name	Object ID	Metric	Message Info
linux1	122ccd51-cd93-4458-98e6-d4f0163e64f0	Memory|Usage (%)	> 90.0
